/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CgtCalculator);
  }
}(this, function(expect, CgtCalculator) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CgtCalculator.CgtEstimatesResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CgtEstimatesResult', function() {
    it('should create an instance of CgtEstimatesResult', function() {
      // uncomment below and update the code to test CgtEstimatesResult
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be.a(CgtCalculator.CgtEstimatesResult);
    });

    it('should have the property annualExclusion (base name: "annual_exclusion")', function() {
      // uncomment below and update the code to test the property annualExclusion
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be();
    });

    it('should have the property estimatedExclusionAvailable (base name: "estimated_exclusion_available")', function() {
      // uncomment below and update the code to test the property estimatedExclusionAvailable
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be();
    });

    it('should have the property estimatedExclusionUsed (base name: "estimated_exclusion_used")', function() {
      // uncomment below and update the code to test the property estimatedExclusionUsed
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be();
    });

    it('should have the property estimatedCgt (base name: "estimated_cgt")', function() {
      // uncomment below and update the code to test the property estimatedCgt
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be();
    });

    it('should have the property estimatedAmountTaxed (base name: "estimated_amount_taxed")', function() {
      // uncomment below and update the code to test the property estimatedAmountTaxed
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be();
    });

    it('should have the property lispCgtInclusionRate (base name: "lisp_cgt_inclusion_rate")', function() {
      // uncomment below and update the code to test the property lispCgtInclusionRate
      //var instane = new CgtCalculator.CgtEstimatesResult();
      //expect(instance).to.be();
    });

  });

}));
