/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CgtCalcEndowmentValues', 'model/CgtCalcEventValues', 'model/CgtEventsCalcResult', 'model/Percentage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CgtCalcEndowmentValues'), require('./CgtCalcEventValues'), require('./CgtEventsCalcResult'), require('./Percentage'));
  } else {
    // Browser globals (root is window)
    if (!root.CgtCalculator) {
      root.CgtCalculator = {};
    }
    root.CgtCalculator.CgtEndowmentEventsCalcResult = factory(root.CgtCalculator.ApiClient, root.CgtCalculator.CgtCalcEndowmentValues, root.CgtCalculator.CgtCalcEventValues, root.CgtCalculator.CgtEventsCalcResult, root.CgtCalculator.Percentage);
  }
}(this, function(ApiClient, CgtCalcEndowmentValues, CgtCalcEventValues, CgtEventsCalcResult, Percentage) {
  'use strict';




  /**
   * The CgtEndowmentEventsCalcResult model module.
   * @module model/CgtEndowmentEventsCalcResult
   * @version V1.1
   */

  /**
   * Constructs a new <code>CgtEndowmentEventsCalcResult</code>.
   * @alias module:model/CgtEndowmentEventsCalcResult
   * @class
   * @extends module:model/CgtEventsCalcResult
   */
  var exports = function() {
    var _this = this;
    CgtEventsCalcResult.call(_this);





  };

  /**
   * Constructs a <code>CgtEndowmentEventsCalcResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CgtEndowmentEventsCalcResult} obj Optional instance to populate.
   * @return {module:model/CgtEndowmentEventsCalcResult} The populated <code>CgtEndowmentEventsCalcResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      CgtEventsCalcResult.constructFromObject(data, obj);
      if (data.hasOwnProperty('effective_cgt_rate')) {
        obj['effective_cgt_rate'] = Percentage.constructFromObject(data['effective_cgt_rate']);
      }
      if (data.hasOwnProperty('cgt_inclusion_rate')) {
        obj['cgt_inclusion_rate'] = Percentage.constructFromObject(data['cgt_inclusion_rate']);
      }
      if (data.hasOwnProperty('disclaimer')) {
        obj['disclaimer'] = ApiClient.convertToType(data['disclaimer'], 'String');
      }
      if (data.hasOwnProperty('cgt_values_tax')) {
        obj['cgt_values_tax'] = CgtCalcEndowmentValues.constructFromObject(data['cgt_values_tax']);
      }
      if (data.hasOwnProperty('cgt_values_func')) {
        obj['cgt_values_func'] = CgtCalcEndowmentValues.constructFromObject(data['cgt_values_func']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(CgtEventsCalcResult.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/Percentage} effective_cgt_rate
   */
  exports.prototype['effective_cgt_rate'] = undefined;
  /**
   * @member {module:model/Percentage} cgt_inclusion_rate
   */
  exports.prototype['cgt_inclusion_rate'] = undefined;
  /**
   * @member {String} disclaimer
   */
  exports.prototype['disclaimer'] = undefined;
  /**
   * @member {module:model/CgtCalcEndowmentValues} cgt_values_tax
   */
  exports.prototype['cgt_values_tax'] = undefined;
  /**
   * @member {module:model/CgtCalcEndowmentValues} cgt_values_func
   */
  exports.prototype['cgt_values_func'] = undefined;



  return exports;
}));


