/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CgtCalcEventValues', 'model/Percentage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CgtCalcEventValues'), require('./Percentage'));
  } else {
    // Browser globals (root is window)
    if (!root.CgtCalculator) {
      root.CgtCalculator = {};
    }
    root.CgtCalculator.CgtEventsCalcResult = factory(root.CgtCalculator.ApiClient, root.CgtCalculator.CgtCalcEventValues, root.CgtCalculator.Percentage);
  }
}(this, function(ApiClient, CgtCalcEventValues, Percentage) {
  'use strict';




  /**
   * The CgtEventsCalcResult model module.
   * @module model/CgtEventsCalcResult
   * @version V1.1
   */

  /**
   * Constructs a new <code>CgtEventsCalcResult</code>.
   * @alias module:model/CgtEventsCalcResult
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>CgtEventsCalcResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CgtEventsCalcResult} obj Optional instance to populate.
   * @return {module:model/CgtEventsCalcResult} The populated <code>CgtEventsCalcResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('income_tax_rate')) {
        obj['income_tax_rate'] = Percentage.constructFromObject(data['income_tax_rate']);
      }
      if (data.hasOwnProperty('default_income_tax_rate')) {
        obj['default_income_tax_rate'] = Percentage.constructFromObject(data['default_income_tax_rate']);
      }
      if (data.hasOwnProperty('cgt_included_in_income_tax')) {
        obj['cgt_included_in_income_tax'] = ApiClient.convertToType(data['cgt_included_in_income_tax'], 'Boolean');
      }
      if (data.hasOwnProperty('cgt_event_values_tax')) {
        obj['cgt_event_values_tax'] = ApiClient.convertToType(data['cgt_event_values_tax'], [CgtCalcEventValues]);
      }
      if (data.hasOwnProperty('cgt_event_values_func')) {
        obj['cgt_event_values_func'] = ApiClient.convertToType(data['cgt_event_values_func'], [CgtCalcEventValues]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Percentage} income_tax_rate
   */
  exports.prototype['income_tax_rate'] = undefined;
  /**
   * @member {module:model/Percentage} default_income_tax_rate
   */
  exports.prototype['default_income_tax_rate'] = undefined;
  /**
   * @member {Boolean} cgt_included_in_income_tax
   */
  exports.prototype['cgt_included_in_income_tax'] = undefined;
  /**
   * @member {Array.<module:model/CgtCalcEventValues>} cgt_event_values_tax
   */
  exports.prototype['cgt_event_values_tax'] = undefined;
  /**
   * @member {Array.<module:model/CgtCalcEventValues>} cgt_event_values_func
   */
  exports.prototype['cgt_event_values_func'] = undefined;



  return exports;
}));


