/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Money'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Money'));
  } else {
    // Browser globals (root is window)
    if (!root.CgtCalculator) {
      root.CgtCalculator = {};
    }
    root.CgtCalculator.CgtCalcProductValues = factory(root.CgtCalculator.ApiClient, root.CgtCalculator.Money);
  }
}(this, function(ApiClient, Money) {
  'use strict';




  /**
   * The CgtCalcProductValues model module.
   * @module model/CgtCalcProductValues
   * @version V1.1
   */

  /**
   * Constructs a new <code>CgtCalcProductValues</code>.
   * Todo
   * @alias module:model/CgtCalcProductValues
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CgtCalcProductValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CgtCalcProductValues} obj Optional instance to populate.
   * @return {module:model/CgtCalcProductValues} The populated <code>CgtCalcProductValues</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('net_expected')) {
        obj['net_expected'] = Money.constructFromObject(data['net_expected']);
      }
      if (data.hasOwnProperty('annual_exclusion')) {
        obj['annual_exclusion'] = Money.constructFromObject(data['annual_exclusion']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Money} net_expected
   */
  exports.prototype['net_expected'] = undefined;
  /**
   * @member {module:model/Money} annual_exclusion
   */
  exports.prototype['annual_exclusion'] = undefined;



  return exports;
}));


