/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Money'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Money'));
  } else {
    // Browser globals (root is window)
    if (!root.CgtCalculator) {
      root.CgtCalculator = {};
    }
    root.CgtCalculator.CgtCalcEventValues = factory(root.CgtCalculator.ApiClient, root.CgtCalculator.Money);
  }
}(this, function(ApiClient, Money) {
  'use strict';




  /**
   * The CgtCalcEventValues model module.
   * @module model/CgtCalcEventValues
   * @version V1.1
   */

  /**
   * Constructs a new <code>CgtCalcEventValues</code>.
   * @alias module:model/CgtCalcEventValues
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>CgtCalcEventValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CgtCalcEventValues} obj Optional instance to populate.
   * @return {module:model/CgtCalcEventValues} The populated <code>CgtCalcEventValues</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fund_ref')) {
        obj['fund_ref'] = ApiClient.convertToType(data['fund_ref'], 'String');
      }
      if (data.hasOwnProperty('weighted_unit_cost')) {
        obj['weighted_unit_cost'] = Money.constructFromObject(data['weighted_unit_cost']);
      }
      if (data.hasOwnProperty('unit_price')) {
        obj['unit_price'] = Money.constructFromObject(data['unit_price']);
      }
      if (data.hasOwnProperty('proceeds')) {
        obj['proceeds'] = Money.constructFromObject(data['proceeds']);
      }
      if (data.hasOwnProperty('base_cost')) {
        obj['base_cost'] = Money.constructFromObject(data['base_cost']);
      }
      if (data.hasOwnProperty('cgt_value')) {
        obj['cgt_value'] = Money.constructFromObject(data['cgt_value']);
      }
      if (data.hasOwnProperty('cgt_event')) {
        obj['cgt_event'] = ApiClient.convertToType(data['cgt_event'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} fund_ref
   */
  exports.prototype['fund_ref'] = undefined;
  /**
   * @member {module:model/Money} weighted_unit_cost
   */
  exports.prototype['weighted_unit_cost'] = undefined;
  /**
   * @member {module:model/Money} unit_price
   */
  exports.prototype['unit_price'] = undefined;
  /**
   * @member {module:model/Money} proceeds
   */
  exports.prototype['proceeds'] = undefined;
  /**
   * @member {module:model/Money} base_cost
   */
  exports.prototype['base_cost'] = undefined;
  /**
   * @member {module:model/Money} cgt_value
   */
  exports.prototype['cgt_value'] = undefined;
  /**
   * @member {Boolean} cgt_event
   */
  exports.prototype['cgt_event'] = undefined;



  return exports;
}));


