/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Money', 'model/Percentage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Money'), require('./Percentage'));
  } else {
    // Browser globals (root is window)
    if (!root.CgtCalculator) {
      root.CgtCalculator = {};
    }
    root.CgtCalculator.CgtEstimatesResult = factory(root.CgtCalculator.ApiClient, root.CgtCalculator.Money, root.CgtCalculator.Percentage);
  }
}(this, function(ApiClient, Money, Percentage) {
  'use strict';




  /**
   * The CgtEstimatesResult model module.
   * @module model/CgtEstimatesResult
   * @version V1.1
   */

  /**
   * Constructs a new <code>CgtEstimatesResult</code>.
   * @alias module:model/CgtEstimatesResult
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>CgtEstimatesResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CgtEstimatesResult} obj Optional instance to populate.
   * @return {module:model/CgtEstimatesResult} The populated <code>CgtEstimatesResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('annual_exclusion')) {
        obj['annual_exclusion'] = Money.constructFromObject(data['annual_exclusion']);
      }
      if (data.hasOwnProperty('estimated_exclusion_available')) {
        obj['estimated_exclusion_available'] = Money.constructFromObject(data['estimated_exclusion_available']);
      }
      if (data.hasOwnProperty('estimated_exclusion_used')) {
        obj['estimated_exclusion_used'] = Money.constructFromObject(data['estimated_exclusion_used']);
      }
      if (data.hasOwnProperty('estimated_cgt')) {
        obj['estimated_cgt'] = Money.constructFromObject(data['estimated_cgt']);
      }
      if (data.hasOwnProperty('estimated_amount_taxed')) {
        obj['estimated_amount_taxed'] = Money.constructFromObject(data['estimated_amount_taxed']);
      }
      if (data.hasOwnProperty('lisp_cgt_inclusion_rate')) {
        obj['lisp_cgt_inclusion_rate'] = Percentage.constructFromObject(data['lisp_cgt_inclusion_rate']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Money} annual_exclusion
   */
  exports.prototype['annual_exclusion'] = undefined;
  /**
   * @member {module:model/Money} estimated_exclusion_available
   */
  exports.prototype['estimated_exclusion_available'] = undefined;
  /**
   * @member {module:model/Money} estimated_exclusion_used
   */
  exports.prototype['estimated_exclusion_used'] = undefined;
  /**
   * @member {module:model/Money} estimated_cgt
   */
  exports.prototype['estimated_cgt'] = undefined;
  /**
   * @member {module:model/Money} estimated_amount_taxed
   */
  exports.prototype['estimated_amount_taxed'] = undefined;
  /**
   * @member {module:model/Percentage} lisp_cgt_inclusion_rate
   */
  exports.prototype['lisp_cgt_inclusion_rate'] = undefined;



  return exports;
}));


