/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CgtCalculator) {
      root.CgtCalculator = {};
    }
    root.CgtCalculator.ForeignExchange = factory(root.CgtCalculator.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ForeignExchange model module.
   * @module model/ForeignExchange
   * @version V1.1
   */

  /**
   * Constructs a new <code>ForeignExchange</code>.
   * @alias module:model/ForeignExchange
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ForeignExchange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ForeignExchange} obj Optional instance to populate.
   * @return {module:model/ForeignExchange} The populated <code>ForeignExchange</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], 'String');
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], 'String');
      }
      if (data.hasOwnProperty('exchange_rate')) {
        obj['exchange_rate'] = ApiClient.convertToType(data['exchange_rate'], 'Number');
      }
    }
    return obj;
  }

  /**
   * From currency
   * @member {String} from
   */
  exports.prototype['from'] = undefined;
  /**
   * From currency
   * @member {String} to
   */
  exports.prototype['to'] = undefined;
  /**
   * ratio to convert from currency to,to currency
   * @member {Number} exchange_rate
   */
  exports.prototype['exchange_rate'] = undefined;



  return exports;
}));


