/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CgtCalculator);
  }
}(this, function(expect, CgtCalculator) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CgtCalculator.CgtCalcEventValues();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CgtCalcEventValues', function() {
    it('should create an instance of CgtCalcEventValues', function() {
      // uncomment below and update the code to test CgtCalcEventValues
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be.a(CgtCalculator.CgtCalcEventValues);
    });

    it('should have the property fundRef (base name: "fund_ref")', function() {
      // uncomment below and update the code to test the property fundRef
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

    it('should have the property weightedUnitCost (base name: "weighted_unit_cost")', function() {
      // uncomment below and update the code to test the property weightedUnitCost
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

    it('should have the property unitPrice (base name: "unit_price")', function() {
      // uncomment below and update the code to test the property unitPrice
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

    it('should have the property proceeds (base name: "proceeds")', function() {
      // uncomment below and update the code to test the property proceeds
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

    it('should have the property baseCost (base name: "base_cost")', function() {
      // uncomment below and update the code to test the property baseCost
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

    it('should have the property cgtValue (base name: "cgt_value")', function() {
      // uncomment below and update the code to test the property cgtValue
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

    it('should have the property cgtEvent (base name: "cgt_event")', function() {
      // uncomment below and update the code to test the property cgtEvent
      //var instane = new CgtCalculator.CgtCalcEventValues();
      //expect(instance).to.be();
    });

  });

}));
