/**
 * CGT calculator
 * Capital Gains Tax Calculator
 *
 * OpenAPI spec version: V1.1
 * Contact: name@momentum.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CgtCalcEndowmentValues', 'model/CgtCalcEventValues', 'model/CgtCalcProductValues', 'model/CgtCalcRequest', 'model/CgtEndowment', 'model/CgtEndowmentEventsCalcRequest', 'model/CgtEndowmentEventsCalcResult', 'model/CgtEndowmentGgBranchEventsCalcRequest', 'model/CgtEndowmentZaEventsCalcRequest', 'model/CgtEstimatedValues', 'model/CgtEstimatesResult', 'model/CgtEvent', 'model/CgtEventsCalcRequest', 'model/CgtEventsCalcResult', 'model/CgtLispEventsCalcResult', 'model/CgtLispGgNaturalEventsCalcRequest', 'model/CgtLispGgTrustEventsCalcRequest', 'model/CgtLispZaCompanyEventsCalcRequest', 'model/CgtLispZaEstimatesCalcRequest', 'model/CgtLispZaNaturalEventsCalcRequest', 'model/CgtLispZaTrustEventsCalcRequest', 'model/EndowmentTaxPortfolio', 'model/EndowmentTaxRates', 'model/Error', 'model/ForeignExchange', 'model/Money', 'model/Percentage', 'api/CgtApi', 'api/ToolApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CgtCalcEndowmentValues'), require('./model/CgtCalcEventValues'), require('./model/CgtCalcProductValues'), require('./model/CgtCalcRequest'), require('./model/CgtEndowment'), require('./model/CgtEndowmentEventsCalcRequest'), require('./model/CgtEndowmentEventsCalcResult'), require('./model/CgtEndowmentGgBranchEventsCalcRequest'), require('./model/CgtEndowmentZaEventsCalcRequest'), require('./model/CgtEstimatedValues'), require('./model/CgtEstimatesResult'), require('./model/CgtEvent'), require('./model/CgtEventsCalcRequest'), require('./model/CgtEventsCalcResult'), require('./model/CgtLispEventsCalcResult'), require('./model/CgtLispGgNaturalEventsCalcRequest'), require('./model/CgtLispGgTrustEventsCalcRequest'), require('./model/CgtLispZaCompanyEventsCalcRequest'), require('./model/CgtLispZaEstimatesCalcRequest'), require('./model/CgtLispZaNaturalEventsCalcRequest'), require('./model/CgtLispZaTrustEventsCalcRequest'), require('./model/EndowmentTaxPortfolio'), require('./model/EndowmentTaxRates'), require('./model/Error'), require('./model/ForeignExchange'), require('./model/Money'), require('./model/Percentage'), require('./api/CgtApi'), require('./api/ToolApi'));
  }
}(function(ApiClient, CgtCalcEndowmentValues, CgtCalcEventValues, CgtCalcProductValues, CgtCalcRequest, CgtEndowment, CgtEndowmentEventsCalcRequest, CgtEndowmentEventsCalcResult, CgtEndowmentGgBranchEventsCalcRequest, CgtEndowmentZaEventsCalcRequest, CgtEstimatedValues, CgtEstimatesResult, CgtEvent, CgtEventsCalcRequest, CgtEventsCalcResult, CgtLispEventsCalcResult, CgtLispGgNaturalEventsCalcRequest, CgtLispGgTrustEventsCalcRequest, CgtLispZaCompanyEventsCalcRequest, CgtLispZaEstimatesCalcRequest, CgtLispZaNaturalEventsCalcRequest, CgtLispZaTrustEventsCalcRequest, EndowmentTaxPortfolio, EndowmentTaxRates, Error, ForeignExchange, Money, Percentage, CgtApi, ToolApi) {
  'use strict';

  /**
   * Capital_Gains_Tax_Calculator.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CgtCalculator = require('index'); // See note below*.
   * var xxxSvc = new CgtCalculator.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CgtCalculator.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CgtCalculator.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CgtCalculator.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version V1.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CgtCalcEndowmentValues model constructor.
     * @property {module:model/CgtCalcEndowmentValues}
     */
    CgtCalcEndowmentValues: CgtCalcEndowmentValues,
    /**
     * The CgtCalcEventValues model constructor.
     * @property {module:model/CgtCalcEventValues}
     */
    CgtCalcEventValues: CgtCalcEventValues,
    /**
     * The CgtCalcProductValues model constructor.
     * @property {module:model/CgtCalcProductValues}
     */
    CgtCalcProductValues: CgtCalcProductValues,
    /**
     * The CgtCalcRequest model constructor.
     * @property {module:model/CgtCalcRequest}
     */
    CgtCalcRequest: CgtCalcRequest,
    /**
     * The CgtEndowment model constructor.
     * @property {module:model/CgtEndowment}
     */
    CgtEndowment: CgtEndowment,
    /**
     * The CgtEndowmentEventsCalcRequest model constructor.
     * @property {module:model/CgtEndowmentEventsCalcRequest}
     */
    CgtEndowmentEventsCalcRequest: CgtEndowmentEventsCalcRequest,
    /**
     * The CgtEndowmentEventsCalcResult model constructor.
     * @property {module:model/CgtEndowmentEventsCalcResult}
     */
    CgtEndowmentEventsCalcResult: CgtEndowmentEventsCalcResult,
    /**
     * The CgtEndowmentGgBranchEventsCalcRequest model constructor.
     * @property {module:model/CgtEndowmentGgBranchEventsCalcRequest}
     */
    CgtEndowmentGgBranchEventsCalcRequest: CgtEndowmentGgBranchEventsCalcRequest,
    /**
     * The CgtEndowmentZaEventsCalcRequest model constructor.
     * @property {module:model/CgtEndowmentZaEventsCalcRequest}
     */
    CgtEndowmentZaEventsCalcRequest: CgtEndowmentZaEventsCalcRequest,
    /**
     * The CgtEstimatedValues model constructor.
     * @property {module:model/CgtEstimatedValues}
     */
    CgtEstimatedValues: CgtEstimatedValues,
    /**
     * The CgtEstimatesResult model constructor.
     * @property {module:model/CgtEstimatesResult}
     */
    CgtEstimatesResult: CgtEstimatesResult,
    /**
     * The CgtEvent model constructor.
     * @property {module:model/CgtEvent}
     */
    CgtEvent: CgtEvent,
    /**
     * The CgtEventsCalcRequest model constructor.
     * @property {module:model/CgtEventsCalcRequest}
     */
    CgtEventsCalcRequest: CgtEventsCalcRequest,
    /**
     * The CgtEventsCalcResult model constructor.
     * @property {module:model/CgtEventsCalcResult}
     */
    CgtEventsCalcResult: CgtEventsCalcResult,
    /**
     * The CgtLispEventsCalcResult model constructor.
     * @property {module:model/CgtLispEventsCalcResult}
     */
    CgtLispEventsCalcResult: CgtLispEventsCalcResult,
    /**
     * The CgtLispGgNaturalEventsCalcRequest model constructor.
     * @property {module:model/CgtLispGgNaturalEventsCalcRequest}
     */
    CgtLispGgNaturalEventsCalcRequest: CgtLispGgNaturalEventsCalcRequest,
    /**
     * The CgtLispGgTrustEventsCalcRequest model constructor.
     * @property {module:model/CgtLispGgTrustEventsCalcRequest}
     */
    CgtLispGgTrustEventsCalcRequest: CgtLispGgTrustEventsCalcRequest,
    /**
     * The CgtLispZaCompanyEventsCalcRequest model constructor.
     * @property {module:model/CgtLispZaCompanyEventsCalcRequest}
     */
    CgtLispZaCompanyEventsCalcRequest: CgtLispZaCompanyEventsCalcRequest,
    /**
     * The CgtLispZaEstimatesCalcRequest model constructor.
     * @property {module:model/CgtLispZaEstimatesCalcRequest}
     */
    CgtLispZaEstimatesCalcRequest: CgtLispZaEstimatesCalcRequest,
    /**
     * The CgtLispZaNaturalEventsCalcRequest model constructor.
     * @property {module:model/CgtLispZaNaturalEventsCalcRequest}
     */
    CgtLispZaNaturalEventsCalcRequest: CgtLispZaNaturalEventsCalcRequest,
    /**
     * The CgtLispZaTrustEventsCalcRequest model constructor.
     * @property {module:model/CgtLispZaTrustEventsCalcRequest}
     */
    CgtLispZaTrustEventsCalcRequest: CgtLispZaTrustEventsCalcRequest,
    /**
     * The EndowmentTaxPortfolio model constructor.
     * @property {module:model/EndowmentTaxPortfolio}
     */
    EndowmentTaxPortfolio: EndowmentTaxPortfolio,
    /**
     * The EndowmentTaxRates model constructor.
     * @property {module:model/EndowmentTaxRates}
     */
    EndowmentTaxRates: EndowmentTaxRates,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The ForeignExchange model constructor.
     * @property {module:model/ForeignExchange}
     */
    ForeignExchange: ForeignExchange,
    /**
     * The Money model constructor.
     * @property {module:model/Money}
     */
    Money: Money,
    /**
     * The Percentage model constructor.
     * @property {module:model/Percentage}
     */
    Percentage: Percentage,
    /**
     * The CgtApi service constructor.
     * @property {module:api/CgtApi}
     */
    CgtApi: CgtApi,
    /**
     * The ToolApi service constructor.
     * @property {module:api/ToolApi}
     */
    ToolApi: ToolApi
  };

  return exports;
}));
